services:
  - type: web
    name: mistral-ocr-app
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y wkhtmltopdf && \
      pip install -r requirements.txt
    startCommand: streamlit run test.py --server.port $PORT --server.enableCORS false
    plan: free
